# Generated by Django 3.2 on 2021-04-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210430_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auterete',
            new_name='auterado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publicado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
